name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install meson and ninja
      run: sudo apt-get install -y ninja-build meson
    - name: setup nobody
      run: set -e && sudo mkdir /home/build && sudo chgrp nobody /home/build && chmod g+ws /home/build && sudo setfacl -m u::rwx,g::rwx /home/build && sudo setfacl -d --set u::rwx,g::rwx,o::- /home/build && sudo echo 'nobody ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
    - name: install criterion
      run: set -e && pushd . && sudo git clone --quiet --depth 1 "https://aur.archlinux.org/criterion.git" "/home/build/criterion" && cd "/home/build/criterion" && sudo runuser -u nobody -- makepkg -si --noconfirm --nocheck && popd
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
