name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install meson and ninja
      run: sudo apt-get install -y ninja-build meson
    - name: install criterion
      run: pushd . && git clone --quiet --depth 1 "https://aur.archlinux.org/criterion.git" "/home/build/criterion" && cd "/home/build/criterion" && runuser -u nobody -- makepkg -si --noconfirm --nocheck && popd
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
