name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install criterion
      run: git clone --recursive https://github.com/Snaipe/Criterion && cd Criterion && meson build && ninja -C build && ninja -c build install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
