name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install meson and ninja
      run: sudo apt-get install -y ninja-build meson
    - name: install criterion
      run: sudo apt-get install libcriterion-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
